# Kamal configuration for ember-app-server (Preview)
# Usage: SERVICE_NAME=my-ember-app HOST=dashboard-preview.weteachme.com kamal deploy -c config/deploy.preview.yml
service: <%= ENV['SERVICE_NAME'] %>
image: weteachme/ember-app-server

proxy:
  host: <%= ENV['HOST'] %>

env:
  clear:
    S3_KEY: preview/index.html
