# Kamal configuration for ember-app-server (Production)
service: <%= ENV['SERVICE_NAME'] || 'ember-app-server' %>
image: weteachme/ember-app-server

registry:
  server: 163645997305.dkr.ecr.ap-southeast-2.amazonaws.com
  username: AWS
  password: <%= ENV["KAMAL_REGISTRY_PASSWORD"] || `aws ecr get-login-password --region ap-southeast-2`.strip %>

# servers
servers:
  - wtm-mcp-servers.taildbf88f.ts.net

proxy:
  ssl: true
  app_port: 3000
  healthcheck:
    path: /up
    interval: 5
    timeout: 5

ssh:
  user: ec2-user
  keys: ["~/.ssh/aws-wtm.pem"]

env:
  clear:
    AWS_REGION: ap-southeast-2
  secret:
    - S3_BUCKET
    - SECRET_KEY
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY

builder:
  dockerfile: Dockerfile
  context: .
  arch: amd64

